lmachens/aeternum-map

src/lib/markerRoutes/router.ts
=> 🐛 Fix deletion of own public routes

src/lib/markers/router.ts
=> ✨ Reduce minimal distance between similar markers

src/app/components/AddComment/AddComment.tsx, src/app/components/AddResources/AddResources.tsx, src/app/components/AddResources/UploadScreenshot.tsx, src/app/components/DeleteButton/DeleteButton.tsx, src/app/components/FavoriteButton/FavoriteButton.module.css, src/app/components/FavoriteButton/FavoriteButton.tsx, src/app/components/MapFilter/MarkersView.tsx, src/app/components/MarkerDetails/MarkerDetails.tsx, src/app/components/MarkerRoutes/MarkerRoute.module.css, src/app/components/MarkerRoutes/MarkerRoute.tsx, src/app/components/MarkerRoutes/MarkerRoutes.tsx, src/app/components/MarkerRoutes/MarkerTypes.tsx, src/app/components/MarkerRoutes/SelectRoute.tsx, src/app/components/MarkerRoutes/api.ts, src/app/components/PublicButton/PublicButton.tsx, src/app/components/User/User.tsx, src/app/contexts/UserContext.tsx, src/lib/auth/collection.ts, src/lib/auth/router.ts, src/lib/auth/types.ts, src/lib/markerRoutes/collection.ts
Fixes #100
https://user-images.githubusercontent.com/10058950/139577406-0987ee9e-4814-4ce2-8b12-7c9c9cbf9e4d.mp4
=> ✨ Favorite marker routes

src/app/components/Comment/Comment.tsx, src/app/components/Confirm/Confirm.module.css, src/app/components/Confirm/Confirm.tsx, src/app/components/DeleteButton/DeleteButton.tsx, src/app/components/MarkerDetails/MarkerDetails.tsx, src/app/components/MarkerDetails/useMarker.ts, src/app/components/MarkerRoutes/MarkerRoute.tsx, src/app/components/Modal/Modal.module.css, src/app/components/Modal/Modal.tsx, src/app/components/PublicButton/PublicButton.tsx, src/app/contexts/ModalContext.tsx
Fixes #134
https://user-images.githubusercontent.com/10058950/139793529-f0439b5c-1bd2-4ea3-935b-c65aecd98bf2.mp4
=> ✨ Add deletion and visibility change confirmation

.eslintrc.json, src/app/components/AddResources/useGeoman.tsx, src/app/components/MarkerRoutes/MarkerRoutes.tsx, src/app/components/MarkerRoutes/SelectRoute.tsx, src/app/components/WorldMap/CanvasMarker.ts, src/app/components/WorldMap/useLayerGroups.ts, src/app/components/WorldMap/useWorldMap.ts, src/app/utils/media.ts, src/app/utils/windows.ts, src/server.ts
Solves some requests of #148
https://user-images.githubusercontent.com/10058950/140644839-0b16729e-e1cc-420e-bb5a-016c8934b7ee.mp4
=> ✨ Add edit mode to route creation

src/app/components/MarkerRoutes/MarkerTypes.tsx, src/app/components/MarkerRoutes/SelectRoute.tsx
=> ✨ Allow routes without markers to support quests

src/app/components/MarkerRoutes/MarkerRoutes.tsx, src/app/components/MarkerRoutes/SelectRoute.tsx, src/app/components/WorldMap/useLayerGroups.ts, src/app/contexts/MarkersContext.tsx, src/lib/markerRoutes/collection.ts
=> Turn on markers on route selection

src/app/contexts/MarkersContext.tsx
Fixes #131
https://user-images.githubusercontent.com/10058950/142060721-e56dd11e-b89c-40ea-ae68-d5a5dff3d505.mp4
=> ✨ Auto target route

src/app/components/MarkerDetails/HideMarkerInput.tsx, src/app/components/MarkerDetails/MarkerDetails.tsx
=> ✨ When hiding a marker, close the marker window automatically

src/app/components/MapFilter/MapFilter.module.css
=> 💄 Move the quickmenu up for shorter cursor travel distance

src/app/components/WorldMap/useLayerGroups.ts
=> 🐛 Markers not correctly hidden and bugged afterwards, when hiding them while moving ingame

src/app/components/ShareLiveStatus/ShareLiveStatus.module.css, src/app/components/ShareLiveStatus/ShareLiveStatus.tsx
=> ✨ Remember last group tokens

src/app/components/AddResources/AddResources.module.css, src/app/components/AddResources/AddResources.tsx, src/app/components/AddResources/DetailsInput.tsx, src/app/components/AddResources/SelectType.tsx, src/app/components/AddResources/TierInput.module.css, src/app/components/AddResources/TierInput.tsx, src/app/components/WorldMap/tooltips.ts, src/app/contexts/MarkersContext.tsx, src/lib/markers/collection.ts, src/lib/markers/router.ts, src/lib/markers/types.ts
=> Add chest tiers and types

src/app/components/Modal/Modal.tsx
=> 🐛 Close modal only on click outside of it

src/app/components/AddResources/AddResources.tsx
=> 🐛 Fix marker details on edit

src/app/components/AddResources/AddResources.tsx, src/lib/markers/router.ts
=> Add discord notifications on marker edit

src/lib/markers/router.ts
=> Fix discord message with undefined title

README.md, src/app/components/WorldMap/rotation.ts
=> Markers are not visible on minimap if rotation is active

src/app/components/MarkerRoutes/SelectRoute.tsx, src/app/components/WorldMap/useLayerGroups.ts
=> 🐛 Editing routes results in loss of markers

src/app/components/MapFilter/MapFilter.tsx
=> 🐛 Fix icon placement on sidebar collapse

src/app/components/Settings/Settings.tsx, src/app/components/WorldMap/usePlayerPosition.ts, src/app/contexts/SettingsContext.tsx
Fixes #67
https://user-images.githubusercontent.com/10058950/143909187-848b7992-f804-4525-8c5c-de4eb430c1e8.mp4
=> ✨ Show a trace line of where you have been

src/app/components/AddResources/SelectType.tsx, src/app/components/MapFilter/MarkersView.tsx, src/app/components/PresetSelect/PresetSelect.module.css, src/app/components/PresetSelect/PresetSelect.tsx, src/app/components/PresetSelect/presets.ts, src/app/contexts/UserContext.tsx, src/lib/auth/collection.ts, src/lib/auth/router.ts, src/lib/auth/types.ts
Fixes #152
https://user-images.githubusercontent.com/10058950/144496469-5f40064d-7adc-40c8-9c67-6967f6c4b0fc.mp4
=> ✨ Add markers presets

src/app/components/WorldMap/useAdaptiveZoom.ts, src/app/contexts/SettingsContext.tsx, src/app/utils/storage.ts
=> ✨ Activate adaptive zoom by default

src/app/components/Settings/Settings.module.css, src/app/components/Settings/Settings.tsx, src/app/components/WorldMap/usePlayerPosition.ts, src/app/contexts/SettingsContext.tsx
=> ✨ Add option to change color of tracing line

src/app/components/ActionControl/ActionCheckbox.tsx, src/app/components/ActionControl/ActionControl.module.css, src/app/components/MapFilter/MarkersView.module.css, src/app/components/MapFilter/MarkersView.tsx, src/app/contexts/MarkersContext.tsx
=> ✨ Add filter to display nodes with comments only

src/app/components/Minimap/MinimapWebsite.tsx, src/app/components/WorldMap/useWorldMap.ts, src/app/minimap.tsx
Fixes #224
Did you know you can press shift key for a box zoom?
=> ✨ Add more zome levels for greater granularity

src/lib/markers/router.ts
=> ✨ Add more details to deleted marker messages

src/app/components/AddResources/useGeoman.tsx
=> 🐛 User is not able to precise place/edit a marker

src/app/components/Comment/Comment.tsx, src/app/components/DeleteButton/DeleteButton.module.css, src/app/components/DeleteButton/DeleteButton.tsx, src/app/components/EditButton/EditButton.module.css, src/app/components/FavoriteButton/FavoriteButton.tsx, src/app/components/ForkButton/ForkButton.module.css, src/app/components/ForkButton/ForkButton.tsx, src/app/components/ForkButton/SelectName.module.css, src/app/components/ForkButton/SelectName.tsx, src/app/components/MarkerRoutes/MarkerRoute.module.css, src/app/components/MarkerRoutes/MarkerRoute.tsx, src/app/components/MarkerRoutes/MarkerRoutes.tsx, src/app/components/MarkerRoutes/SelectRoute.tsx, src/app/contexts/MarkersContext.tsx, src/app/globals.css, src/lib/markerRoutes/collection.ts, src/lib/markerRoutes/router.ts, src/lib/markerRoutes/types.ts
Fixes #243
https://user-images.githubusercontent.com/10058950/150209693-cd6c7781-8695-498a-838a-7777be5ab60a.mp4
=> ✨ Add forks to customize existing routes

src/app/components/MarkerRoutes/MarkerRoutes.tsx
=> 🐛 The search box for routes does not work when you filter by region.

dist/overwolf/manifest.json, src/app/components/AppHeader/AppHeader.tsx, src/app/components/WorldMap/CanvasMarker.ts, src/app/components/WorldMap/WorldMap.module.css, src/app/components/WorldMap/actions.ts, src/app/components/WorldMap/useLayerGroups.ts, src/app/sender/AppHeader.tsx, src/app/sender/Settings.tsx
Fixes #55
https://user-images.githubusercontent.com/10058950/150635998-b62a10e0-747e-4c4e-b02d-b6664a8e57e1.mp4
=> ✨ Add manual respawn timer

src/app/components/AddComment/AddComment.tsx, src/app/components/AddComment/ReportIssue.module.css, src/app/components/AddComment/ReportIssue.tsx, src/app/components/AddComment/api.ts, src/app/components/Comment/Comment.module.css, src/app/components/Comment/Comment.tsx, src/app/components/MapFilter/MarkersView.tsx, src/app/components/MarkerDetails/MarkerDetails.tsx, src/app/components/MarkerDetails/useMarker.ts, src/app/components/WorldMap/CanvasMarker.ts, src/app/components/WorldMap/useLayerGroups.ts, src/app/contexts/MarkersContext.tsx, src/lib/comments/collection.ts, src/lib/comments/router.ts, src/lib/comments/types.ts, src/lib/markers/collection.ts, src/lib/markers/router.ts, src/lib/markers/types.ts
=> ✨ Option to report invalid markers

src/app/components/MapFilter/mapFilters.ts
=> 💬 Rename  'Control Point' to 'Conquer'

src/app/components/AddResources/AddResources.tsx, src/app/components/AddResources/DetailsInput.tsx, src/app/components/AddResources/SizeInput.tsx, src/app/components/MapFilter/FilterSelection.tsx, src/app/components/MapFilter/FilterWithOptions.module.css, src/app/components/MapFilter/MarkerSection.tsx, src/app/components/MapFilter/mapFilters.ts, src/app/components/WorldMap/actions.ts, src/app/contexts/FiltersContext.tsx, src/lib/markers/types.ts
=> ✨ Add missing XS and XL sizes for trees

src/app/components/MarkerRoutes/MarkerRoutes.tsx
Sort by match didn't respect new marker sizes
=> 🐛 Fix sort by match

src/app/components/MapFilter/mapFilters.ts
=> 🔥 Remove medleyfair nodes

packages/ui/components/PresetSelect/PresetSelect.tsx, packages/ui/utils/filtersStore.tsx
=> Fix saving presets
